### ISSUE TITLE
Error when initializing

### ISSUE THREAD

**Issue by jbouduin** [opf/OpenProjectExcel#2]
Me again…
Still trying to use the XL for the first time. When initializing I get the following error:
![error message](https://user-images.githubusercontent.com/44770683/51965953-5d7bb600-246b-11e9-90f9-8d0860f9d351.jpg)

My Settings are like this:
![selectproject](https://user-images.githubusercontent.com/44770683/51966251-4be6de00-246c-11e9-9a84-3a4df88cdf00.jpg)

As mentioned in #1 : Debugging pointed out that this happens when trying to retrieve types using SubUrlStr = "Projects/andere/types". Dokumentation of the API (http://docs.openproject.org/apiv3-doc/#types-types-by-project-get) specifies that an integer (Project ID) should be used. 

When using curl to simulate the API-calls as executed by the Makro:
![curl](https://user-images.githubusercontent.com/44770683/51966721-8d2bbd80-246d-11e9-9df2-41c3501bb583.jpg)

I'm a lousy VBA developer, otherwise I would solve it myself.
I have this as well with the file from Master branch, as with the one tagged v0.5.1

best regards
Johan

**Comment by bpetraus** [comment]
Hi Johan,

the vba code normally replaces identifier by project id. Seems to me, that this doesnt work properly.

What is pretty obvious in the formular, "Andere" should definitely be completely lowercase. Are you sure, that this is the identifier, not the name of the project?

Bad example, because name and identifier are here nearly the same, but to make clear, what i'm trying to make sure:

![image](https://user-images.githubusercontent.com/38315559/51998698-6abf9180-24b9-11e9-85d6-7944a3c8feb7.png)

Regards

Bernd

**Comment by jbouduin** [comment]
Hello Bernd,

my mistake. The projects name is "Andere", the identifier is something completely different as I renamed the project a while ago.

Sorry for the annoyance
Johan

**Comment by bpetraus** [comment]
Hi Johan,

ok, good to know. Thank you for your response!

Best Regards

Bernd
