### ISSUE TITLE
Finish Date changes automatically. 

### ISSUE THREAD

**Issue by fpondaag** [opf/OpenProjectExcel#44]
Finish date content changes automatically.
for example,  7/11/2021 (D/M/YYYY) after clicking on the update/upload button, The Finish Date content changed into 11/7/2021 (11 Jul 2021).

Causing an error message like this:
> 422 - Finish date must be greater than or equal to the start date. (Details: {"_type":"Error","errorIdentifier":"urn:openproject-org:api:v3:errors:PropertyConstraintViolation","message":"Finish date must be greater than or equal to the start date.","_embedded":{"details":{"attribute":"dueDate"}}})

**Comment by bpetraus** [comment]
hi @fpondaag,

can you provide some anonymous screenshots?

Best

Bernd

**Comment by tvdneto** [comment]
Hello @bpetraus ,

I am also getting this issue. Before I start the upload, the task is as below (DD/MM/YYYY):

![Before](https://user-images.githubusercontent.com/72450343/161812646-128cfd62-c8d0-48bf-abf2-f039f5e15e28.png)

And after I select to upload, I get the below errors in the file:

![After](https://user-images.githubusercontent.com/72450343/161812714-a3465bec-5736-408a-af1b-fb14c6f1eaae.png)

I thought it was an error in the date format, since I had OpenProject with "DD/MM/YYYY" format, and the excel sync only worked with USA format, so I later changed the excel with "MM/DD/YYYY" but had the same issue.

Any help on this is much appreciated, since I have a lot of projects to import into OP (migrating user).

Thanks!

**Comment by tvdneto** [comment]
Hello @bpetraus , any idea as to why this is happening? Even if I use the same date format it still comes to this issue. It would be great to get some feedback on this. Thanks!

**Comment by bpetraus** [comment]
Hi @tvdneto , 
1. did u tried this format: dd.mm.yyyy, e.g. 11.05.2022?
2. what format do you get, when you download workpackages, that have beend created manually in your OpenProject instance?
Best
Bernd

**Comment by tvdneto** [comment]
Hello @bpetraus,

When I "download" the tasks, they show in the excel file as "MM/DD/YY". If I "upload/update" after the initial "download", it gets the errors. Basically like this:

Original dates of each task (I have input these manually in OpenProject):
- Subtask 1.1, Start = August 16, 2021 / End = January 8, 2022
- Subtask 1.2, Start = June 22, 2022 / End = August 21, 2022
OBS: date setting in OpenProject is YYYY-MM-DD

1 - I "download" the tasks and this shows up:
![image](https://user-images.githubusercontent.com/72450343/167867535-0406c2f7-09a0-4302-81ec-219ad180b89c.png)
You can see that the START and END dates already have different formatting. They are still dates, but with different format.

2 - I click "upload/update" without editing anything, just update the file and this happens:
![image](https://user-images.githubusercontent.com/72450343/167868475-77d4252b-bdc6-4800-8719-db9a9fccd17d.png)
The formats change again, but this time, the dates are not in proper format and are not being considered as dates. The issue is on this change of formatting, where sometimes the dates would change (from 01/08 (February 8) to 08/01 (August 1).

I have tried using the format which the excel file is set to "MM/DD/YY", but this behavior still occurs. Do I need to have OpenProejct set to this format in order to avoid the issue?

Thanks for the attention!

**Comment by pdemaret** [comment]
Hello, I see the same problem on my installation, where dates months and days are "swapped" between download and upload via the excel sheet.
I launched a standard instance of openproject, and only perform download and upload on the demo project. All time format set to YYY-MM-DD, in windows, excel as in OP.

First download : all fine, data is exactly what it should be.
![Screenshot 2022-06-05 at 14 55 34](https://user-images.githubusercontent.com/12196916/172051581-cae2ed3b-2691-4540-a0bf-1eb9779abc81.png)

Then I just upload the same data, with no change in the excel sheet: 
![Screenshot 2022-06-05 at 14 56 19](https://user-images.githubusercontent.com/12196916/172051618-c87430b7-5421-4681-b19d-96578ff5f6d7.png)
As you can see, lines 3, 6 7 and 8 are now in error, because of a swap between month and day in the date.

Thank you for your attention, and possible help !

**Comment by bpetraus** [comment]
Hi @tvdneto  Hi @pdemaret 

@tvdneto sorry for responding that late. I didnt recevice a notifaction before @pdemaret commented.

This is a excel problem. OpenProject only accepts 'YYYY-MM-DD (ISO 8601 date)'. So the Excel files tries to convert whatever is typed in the cell to that format, before uploading. 

Whats going on here is, that Excel tries to "fix" a date automatically. That unfortunately often goes wrong. By using the cell formation you could try:

* find a format, that works in your case (depending on language ect.)
* try to format it as text and fill it manually with "YYYY-MM-DD"

Best 

Bernd

**Comment by tvdneto** [comment]
Hello @bpetraus ,

Thank you for the information. Is there no way to override the excel issue in the VBA? I have tried multiple date formats but this just keeps happening.

Even tried changing system date settings, but no success.

Thanks again!

**Comment by bpetraus** [comment]
Hi @tvdneto ,

did you tried to format the affected columns to "text", in order to avoid auto-formating?

Best

Bernd

**Comment by tvdneto** [comment]
Hello @bpetraus,

No I did not 🤦‍♂️ , and YES **that resolves this issue**. Best solutions are the simple ones. I would like to mark your reply as an answer but I am not the owner of this thread...

Thank you so much for your support and time! This will save a lot of my time migrating to OpenProject.

Cheers!

**Comment by pdemaret** [comment]
Hell @bpetraus, I confirm that setting in excel the format of all the date columns to text resolves the issue.
Thank you very much !

**Comment by bpetraus** [comment]
Great, thank you for your feedback!
